const paths = {
  home: '/',
  category: '/category',
  mangaDetail: '/manga-detail',
  chapterDetail: '/manga/chapter',
  discover: '/kham-pha',
  rankings: '/bang-xep-hang',
  community: '/cong-dong',
  communityTopic: '/cong-dong/topic/:id',
  postDetail: '/cong-dong/post/:id',
  authorHub: '/tac-gia-nhom-dich',
  teamProfile: '/nhom/:id',
  releaseCalendar: '/lich-phat-hanh',
  advancedSearch: '/tim-kiem-nang-cao',
  search: '/search',
  library: '/library',
  notifications: '/thong-bao',
  dashboard: '/dashboard',
  upload: '/dang-truyen',
  report: '/bao-cao',
  profile: '/ho-so',
  publicProfile: '/user/:id',
  recommendations: '/goi-y',
  changePassword: '/doi-mat-khau',
  myComics: '/truyen-cua-toi',
  login: '/dang-nhap',
  register: '/dang-ky',
  forgotPassword: '/quen-mat-khau',

  // admin
  adminDashboard: '/admin/dashboard',
  userManagement: '/admin/users',
  badgeManagement: '/admin/badges',
  systemStats: '/admin/stats',
  adminSettings: '/admin/settings',
  adManagement: '/admin/ads',
  mangaManagement: '/admin/manga',
  mangaReview: '/admin/manga/:id/reviews',
  mangaComment: '/admin/manga/:id/comments',
  teamManagement: '/admin/teams',
  teamMember: '/admin/teams-members/:id',
  topicManagement: '/admin/topics',
  postManagement: '/admin/posts/:id',
  recommendationControl: '/admin/recommendations-control',
  communityModeration: '/admin/community-moderation',
  userSecurity: '/admin/user-security',
  rbacManagement: '/admin/rbac',
  collectionAudit: '/admin/collection-audit',
  opsMonitoring: '/admin/ops-monitoring',
  securityAudit: '/admin/security-audit',
};

export default paths;
