const paths = {
  home: '/',
  category: '/category',
  mangaDetail: '/manga-detail',
  chapterDetail: '/manga/chapter',
  discover: '/kham-pha',
  rankings: '/bang-xep-hang',
  community: '/cong-dong',
  communityTopic: '/cong-dong/topic/:id',
  postDetail: '/cong-dong/post/:id',
  authorHub: '/tac-gia-nhom-dich',
  teamProfile: '/nhom/:id',
  releaseCalendar: '/lich-phat-hanh',
  advancedSearch: '/tim-kiem-nang-cao',
  search: '/search',
  library: '/library',
  notifications: '/thong-bao',
  dashboard: '/dashboard',
  upload: '/dang-truyen',
  report: '/bao-cao',
  profile: '/ho-so',
  recommendations: '/goi-y',
  changePassword: '/doi-mat-khau',
  myComics: '/truyen-cua-toi',
  login: '/dang-nhap',
  register: '/dang-ky',
  forgotPassword: '/quen-mat-khau',
  admin: '/admin',
};

export default paths;
